/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.Student.Student;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.StudentRole.UpdateStudentJPanel;

/**
 *
 * @author shreyas
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Student student;
    ImageIcon productImage;
    Network network;
    
    
    private boolean ageValid = true;
    private boolean zipValid = true;
    private boolean heightValid = true;
    private boolean weightValid = true;

    public StudentWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.system = business;
        
        
        student = userAccount.getStudent();
        return;
    }

    

    private boolean usernamePatternCorrect(String val) {
        Pattern p = Pattern.compile("^.+@[^\\.].*\\.[a-z]{2,}$");
        Matcher m = p.matcher(val);
        boolean b = m.matches();
        return b;
    }

    private boolean namePatternCorrect(String val1) {
        Pattern p = Pattern.compile("^[a-zA-Z ]+$");
        Matcher m = p.matcher(val1);
        boolean b = m.matches();
        return b;
    }

    private boolean addressPatternCorrect(String val2) {
        Pattern p = Pattern.compile("^[a-z A-Z 0-9 #/-]+$");
        Matcher m = p.matcher(val2);
        boolean b = m.matches();
        return b;
    }

    private boolean cityPatternCorrect(String val3) {
        Pattern p = Pattern.compile("^[a-zA-Z ]+$");
        Matcher m = p.matcher(val3);
        boolean b = m.matches();
        return b;
    }

    private boolean passwordPatternCorrect(String val4) {
        Pattern p1;
        p1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1 = p1.matcher(String.valueOf(val4));
        boolean b1 = m1.matches();
        return b1;
    }

    private boolean numberPatternCorrect(String val5) {
        Pattern p = Pattern.compile("^[0-9]$");
        Matcher m = p.matcher(val5);
        boolean b = m.matches();
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalysis = new javax.swing.JButton();
        btnMaintainReq = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        greetLbl = new javax.swing.JLabel();
        placeOrderBtn1 = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        btnUpdateProfile = new javax.swing.JButton();
        btnUniversityStore = new javax.swing.JButton();
        btnStationeryStore = new javax.swing.JButton();
        btnFoodStore = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnalysis.setBackground(new java.awt.Color(102, 255, 255));
        btnAnalysis.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnAnalysis.setForeground(new java.awt.Color(51, 51, 51));
        btnAnalysis.setText("Health Club");
        btnAnalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalysisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnalysisMouseExited(evt);
            }
        });
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });
        add(btnAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, 70));

        btnMaintainReq.setBackground(new java.awt.Color(102, 255, 255));
        btnMaintainReq.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnMaintainReq.setForeground(new java.awt.Color(51, 51, 51));
        btnMaintainReq.setText("Housing Maintenence");
        btnMaintainReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaintainReqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaintainReqMouseExited(evt);
            }
        });
        btnMaintainReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintainReqActionPerformed(evt);
            }
        });
        add(btnMaintainReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 340, 70));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Welcome,");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 120, 40));

        greetLbl.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        greetLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(greetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 330, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        placeOrderBtn1.setBackground(new java.awt.Color(102, 255, 255));
        placeOrderBtn1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        placeOrderBtn1.setForeground(new java.awt.Color(51, 51, 51));
        placeOrderBtn1.setText("Housing Inventory Requirements");
        placeOrderBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                placeOrderBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                placeOrderBtn1MouseExited(evt);
            }
        });
        placeOrderBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtn1ActionPerformed(evt);
            }
        });
        add(placeOrderBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 340, 80));

        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/StudentWorkArea.jpg"))); // NOI18N
        add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 186, 600, 320));

        btnUpdateProfile.setBackground(new java.awt.Color(102, 255, 255));
        btnUpdateProfile.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnUpdateProfile.setForeground(new java.awt.Color(51, 51, 51));
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });
        add(btnUpdateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 150, 40));

        btnUniversityStore.setBackground(new java.awt.Color(102, 255, 255));
        btnUniversityStore.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnUniversityStore.setForeground(new java.awt.Color(51, 51, 51));
        btnUniversityStore.setText("University Store");
        btnUniversityStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUniversityStoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUniversityStoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUniversityStoreMouseExited(evt);
            }
        });
        btnUniversityStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniversityStoreActionPerformed(evt);
            }
        });
        add(btnUniversityStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 340, 70));

        btnStationeryStore.setBackground(new java.awt.Color(102, 255, 255));
        btnStationeryStore.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnStationeryStore.setForeground(new java.awt.Color(51, 51, 51));
        btnStationeryStore.setText("Stationery Store");
        btnStationeryStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStationeryStoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStationeryStoreMouseExited(evt);
            }
        });
        btnStationeryStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStationeryStoreActionPerformed(evt);
            }
        });
        add(btnStationeryStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 200, 50));
        btnStationeryStore.setVisible(false);

        btnFoodStore.setBackground(new java.awt.Color(102, 255, 255));
        btnFoodStore.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnFoodStore.setForeground(new java.awt.Color(51, 51, 51));
        btnFoodStore.setText("Food Store");
        btnFoodStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFoodStoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFoodStoreMouseExited(evt);
            }
        });
        btnFoodStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodStoreActionPerformed(evt);
            }
        });
        add(btnFoodStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 200, 50));
        btnFoodStore.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
            //                                                                  JPanel userProcessContainer, Student student, EcoSystem system, UserAccount userAccount, Enterprise enterprise, Network network
        StudentAnalysisJPanel studentAnalysisJPanel = new StudentAnalysisJPanel(userProcessContainer, student, system, userAccount, enterprise, network);
        userProcessContainer.add("StudentAnalysisJPanel", studentAnalysisJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnMaintainReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintainReqActionPerformed
        // TODO add your handling code here:
        RaiseRequestJPanel requestPanel = new RaiseRequestJPanel(userProcessContainer, student, system, userAccount, enterprise, network);
        userProcessContainer.add("StudentRequestJPanel", requestPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMaintainReqActionPerformed

    private void placeOrderBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtn1ActionPerformed
        PlaceOrderJPanel placeOrder = new PlaceOrderJPanel(userProcessContainer, student, system, userAccount, enterprise, network);
        userProcessContainer.add("StudentAnalysisJPanel", placeOrder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_placeOrderBtn1ActionPerformed

    private void btnAnalysisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalysisMouseEntered
        // TODO add your handling code here:
        hideStoreButtons();
        imgLabel.setIcon(new ImageIcon(getClass().getResource("/userinterface/images/fitness.jpg")));
    }//GEN-LAST:event_btnAnalysisMouseEntered

    private void btnAnalysisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalysisMouseExited
        // TODO add your handling code here:
        productImage = null;
        imgLabel.setIcon(productImage);
        
    }//GEN-LAST:event_btnAnalysisMouseExited

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        // TODO add your handling code here: JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network
        UpdateStudentJPanel updateStudentJPanel = new UpdateStudentJPanel(userProcessContainer, enterprise, organization, userAccount, system, network);
        userProcessContainer.add("UpdateStudentJPanel", updateStudentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
      
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void placeOrderBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderBtn1MouseEntered
        // TODO add your handling code here:
        imgLabel.setIcon(new ImageIcon(getClass().getResource("/userinterface/images/house.png")));
        hideStoreButtons();
    }//GEN-LAST:event_placeOrderBtn1MouseEntered

    private void btnMaintainReqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaintainReqMouseEntered
        // TODO add your handling code here:
        imgLabel.setIcon(new ImageIcon(getClass().getResource("/userinterface/images/ch.jpeg")));
        hideStoreButtons();
    }//GEN-LAST:event_btnMaintainReqMouseEntered

    private void placeOrderBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderBtn1MouseExited
        // TODO add your handling code here:
        productImage = null;
        imgLabel.setIcon(productImage);
    }//GEN-LAST:event_placeOrderBtn1MouseExited

    private void btnMaintainReqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaintainReqMouseExited
        // TODO add your handling code here:
        productImage = null;
        imgLabel.setIcon(productImage);
    }//GEN-LAST:event_btnMaintainReqMouseExited

    private void btnUniversityStoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUniversityStoreMouseEntered
        // TODO add your handling code here:
        imgLabel.setIcon(new ImageIcon(getClass().getResource("/userinterface/images/StudentStore.png")));
        hideStoreButtons();
    }//GEN-LAST:event_btnUniversityStoreMouseEntered

    private void btnUniversityStoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUniversityStoreMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUniversityStoreMouseExited

    private void btnUniversityStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniversityStoreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUniversityStoreActionPerformed

    private void btnStationeryStoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStationeryStoreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStationeryStoreMouseEntered

    private void btnStationeryStoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStationeryStoreMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStationeryStoreMouseExited

    private void btnStationeryStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStationeryStoreActionPerformed
        // TODO add your handling code here:
        StudentStationeryJPanel requestPanel = new StudentStationeryJPanel(userProcessContainer, student, system, userAccount, enterprise, network);
        userProcessContainer.add("StudentStationeryJPanel", requestPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStationeryStoreActionPerformed

    private void btnFoodStoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodStoreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFoodStoreMouseEntered

    private void btnFoodStoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodStoreMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFoodStoreMouseExited

    private void btnFoodStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodStoreActionPerformed
        // TODO add your handling code here:
        StudentFoodStoreJPanel requestPanel = new StudentFoodStoreJPanel(userProcessContainer, student, system, userAccount, enterprise, network);
        userProcessContainer.add("StudentFoodStoreJPanel", requestPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFoodStoreActionPerformed

    private void btnUniversityStoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUniversityStoreMouseClicked
        // TODO add your handling code here:
        showStoreBusston();
    }//GEN-LAST:event_btnUniversityStoreMouseClicked

    private void hideStoreButtons(){
        
        btnStationeryStore.setVisible(false);
        btnFoodStore.setVisible(false);
    }

    private void showStoreBusston(){
        btnStationeryStore.setVisible(true);
        btnFoodStore.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnFoodStore;
    private javax.swing.JButton btnMaintainReq;
    private javax.swing.JButton btnStationeryStore;
    private javax.swing.JButton btnUniversityStore;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JLabel greetLbl;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton placeOrderBtn1;
    // End of variables declaration//GEN-END:variables
}
